Repository Atraxus/dit, pull requests merged in 2023-07, with the labels that each got.

#14 CI improvements
  .github/problem_matchers.json
  .github/workflows/test_project.yaml
  dit-core/src/lib.rs
  dit-core/src/peer.rs
  dit-core/src/peer/proto.rs
  dit/src/lib.rs
Labels: S-waiting-on-review, C-enhancement, A-meta

#15 CI: ensure lockfile is up to date
  .github/workflows/test_project.yaml
  Cargo.lock
Labels: S-waiting-on-review, A-meta

#13 DHT Part II: Fingers
  dit-core/src/peer.rs
  dit-core/src/peer/proto.rs
  dit-core/src/peer/types.rs
  dit/src/lib.rs
Labels: A-dht, C-enhancement

#17 protocol improvements
  Cargo.lock
  dit-core/Cargo.toml
  dit-core/src/codec.rs
  dit-core/src/lib.rs
  dit-core/src/peer.rs
  dit-core/src/peer/proto.rs
Labels: A-dht, C-cleanup

#11 Daemon
  dit-core/src/daemon.rs
  dit-core/src/peer.rs
  dit/src/lib.rs
Labels: S-waiting-on-author, A-daemon, C-enhancement

#18 Config
  Cargo.lock
  dit-core/Cargo.toml
  dit-core/src/config.rs
  dit-core/src/daemon.rs
  dit-core/src/dit-config.toml
  dit-core/src/lib.rs
  dit-core/src/peer.rs
  dit-core/src/peer/types.rs
  dit-core/src/store.rs
  dit/src/lib.rs
Labels: S-waiting-on-review, A-dht, A-daemon, A-cli, A-store, C-enhancement

#21 DHT Part III: Routing
  Cargo.lock
  dit-core/Cargo.toml
  dit-core/src/config.rs
  dit-core/src/dit-config.toml
  dit-core/src/peer.rs
  dit-core/src/peer/types.rs
  dit-core/tests/peer.rs
Labels: C-bug, S-waiting-on-review, A-dht, C-enhancement

#20 Bootstrapping for daemon
  dit-core/src/daemon.rs
  dit/src/lib.rs
Labels: S-waiting-on-review, A-daemon, C-enhancement

#22 DHT Part IV: Announce/Fetch
  dit-core/src/peer.rs
  dit-core/src/peer/proto.rs
  dit-core/tests/peer.rs
Labels: A-dht

#19 Store
  dit-core/src/peer/types.rs
  dit-core/src/store.rs
Labels: S-waiting-on-review, A-store, C-enhancement

#24 file transfer, part II
  .github/workflows/test_project.yaml
  dit-core/Cargo.toml
  dit-core/src/daemon.rs
  dit-core/src/peer.rs
  dit-core/src/peer/types.rs
  dit-core/src/store.rs
  dit/src/lib.rs
Labels: S-waiting-on-author, A-daemon, A-cli, A-store
